### ISSUE TITLE
Consider defining a standard relation_name for plain old data

### ISSUE THREAD

**Issue by bradh** [jyutzler/geopackage-related-tables#27]
It would be useful if we had a way to communicate that the related_table content is "plain old data" (INTEGER, TEXT, REAL values), such that clients could present that.

That might imply another requirements class (so that every column is one of the expected types).

At the very least we need to know what to put in the `relation_name` for a non-media relationship.

**Comment by tabinfl** [comment]
Could punt to `other` for now, at least until we get around to defining other types of relationships (maybe beyond too).

**Comment by jyutzler** [comment]
Yes, this would be another requirements class. 

My preference would be to punt on this as part of the IE unless you or someone else is willing to test it out (producer and consumer).

Something we're going to have to consider is how we're going to version extensions since it is plausible that we will publish this extension with 2 requirements classes and come back later and add more. But that's a SWG issue.

**Comment by bradh** [comment]
I would like to have a go at this, unless there are objections. I'm currently thinking `simple_attributes`.

I don't have a concept for the extension versioning, but it seems like a general problem. Perhaps GPKG 1.3 should have an `extension_version` column in the `gpkg_extensions` table.

**Comment by jyutzler** [comment]
No objection.

**Comment by bradh** [comment]
Resolved by #30
